site:
  title: Boost.Unordered
  start_page: unordered::index.adoc
content:
  sources:
  - url: ..
    start_path: doc
    branches: HEAD
output:
  dir: html
ui:
  bundle:
    url: https://github.com/cmazakas/unordered-ui-bundle/raw/450505aa457796028a36e9d712e5d52f9f394c1a/ui-bundle.zip
  output_dir: unordered/_
